[package]
name = "advent"
version = "2023.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
colored = "2.0"
regex = "1.10"
reqwest = { version = "0.11", features = ["blocking"]}
